---
# tasks file for cert

- name: Generate an OpenSSL public key in PEM format
  community.crypto.x509_certificate:
    path: "/etc/ssl/{{domain}}/public/{{domain}}.crt"
    privatekey_path: "/etc/ssl/{{domain}}//private/{{domain}}.key"
    csr_path: "/etc/ssl/{{domain}}/csr/{{domain}}.csr"
    ownca_path: /etc/ssl/public/rootCA.pem
    ownca_privatekey_path: /etc/ssl/private/rootCA.key  
    provider: ownca
    privatekey_passphrase: ansible
    ownca_privatekey_passphrase: ansible
    subject_alt_name:
      - ec.fivemarkers.com
- name: ensure the below directories are created on target server
  hosts: ansible
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/etc/ssl/public"
    - "/etc/ssl/csr"
    - "/etc/ssl/private"