
- name: create SSL directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/etc/ssl/{{domain}}/public"
    - "/etc/ssl/{{domain}}/csr"
    - "/etc/ssl/{{domain}}/private"

- name: generate private key and csr
  script: "ssl.sh {{domain}}"